name: 'Build jekyll site from dev container and push to specified environment via rsync' 

inputs:
  registry_image_name:
    description: “imageName for devcontainer”
    required: true
  registry_token:
    description: "GitHub token for registry"
    required: true
  registry_user:
    description: "GitHub user for registry"
    required: true
  rsync_user:
    description: “Username for rsync”
    required: true
  rsync_host:
    description: "Host for rsync"
    required: true
  rsync_key:
    description: "Private SSH key for rsync"
    required: true
  rsync_target:
    description: "Target path for rsync"
    required: true
  rsync_source:
    description: "Source path for rsync"
    required: true



runs:
  using: "composite"
  steps:

    - name: Checkout (GitHub)
      uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2 
      with:
        registry: ghcr.io
        username: ${{inputs.registry_user}}
        password: ${{inputs.registry_token}}

    - name: Build and run Dev Container task
      uses: devcontainers/ci@v0.3
      with:
        # Change this to point to your image name
        imageName: ${{inputs.registry_image_name}}
        # Change this to be your CI task/script
        runCmd: |
          bundle
          jekyll build

    - name: Upload to dev environment via rsync
      uses: up9cloud/action-rsync@master
      env:
        USER: ${{inputs.rsync_user}}
        HOST: ${{inputs.rsync_host}}
        KEY: ${{inputs.rsync_key}}
        TARGET: ${{inputs.rsync_target}}
        SOURCE: ${{inputs.rsync_source}}

